apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-dev-pv
  annotations:
    pv.kubernetes.io/provisioned-by: hspc.csi.hitachi.com
spec:
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  csi:
    fsType: ext4
    volumeAttributes:
      connectionType: fc
      ports: CL1-A, CL2-A
    volumeHandle: 01--scsi--938000745403--153--spc-9d160541ed
    driver: hspc.csi.hitachi.com
    controllerExpandSecretRef:
      name: secret-dc1-e1090
      namespace: hspc01
    controllerPublishSecretRef:
      name: secret-dc1-e1090
      namespace: hspc01
  storageClassName: sc-gold-dc1
